project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  title: "MAIRI GKALIANIDOU"
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - href: projects.qmd
        text: PROJECTS
      - href: contacts.qmd
        text: CONTACTS
      - href: tab-one/tab-one-index.qmd
        text: PRESENTATION
      - href: tab-iframe/iframe-index.qmd
        text: SURVEY
      - href: tab2-iframe/iframe2-index.qmd
        text: VISUALIZATION 
    logo: images/logo_tepak.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

